### ISSUE TITLE
Cutting a release?

### ISSUE THREAD

**Issue by daemonsy** [micromdm/nanomdm#31]
Hi, there's been a lot of improvements since the last release in June 2021. 

As much as we can, we'd like to rely on official releases. Was wondering: 

1. Can we get a release cut? 😸 
2. Maybe it's good to discuss what do releases mean for NanoMDM and if it makes sense to have a certain type of cadence of cutting releases? 

e.g. I can imagine if there was a time or feature based release schedule that followed some level of semantic versioning in spirit, we would try our best frequently update to the nearest minor version and run some form of QA process before a major / breaking version change.

**Comment by jessepeterson** [comment]
I do agree about a newer release. It's been on my todo list for a bit, actually.

However I also like your idea for discussion on a more regular release schedule/cadence. Maybe a topic for this Thursday's office hours. :) MicroMDM's releases have not been formalized either and due for a release (really just waiting for micromdm/micromdm#760) but could probably benefit from having its release cadence a bit more regular, too.

**Comment by daemonsy** [comment]
Thanks! Here's an outline of how we imagine deployment pipeline to work with having regular releases. Hope it's useful context to you for discussion. 

In the ideal world, every logical PR could be a minor release when there are no breaking changes, encourages code to be always shippable. In reality, if there was a regular cadence, once every two weeks, we'll always try to keep on the latest release. 

- We deploy docker containers to EKS 
- This is managed by a CD pipeline 
- The pipeline declares which version of nanomdm it deploys in a config yaml file
- When nanomdm cuts a new release, probably do some Github actions automation to send our pipeline a PR and highlights the migrations that will need to be run 
- We merge the PR and it deploys that new version now

**Comment by jessepeterson** [comment]
Released v0.2: https://twitter.com/micromdm_io/status/1433547617883938816
