### ISSUE TITLE
Publish Docker image

### ISSUE THREAD

**Issue by samcat116** [micromdm/nanomdm#33]
Since there is already a Dockerfile in the repo and its actively using GitHub Actions, it would be great to publish a container to Docker Hub or the Github Container registry for easy access. Personally it would make creating a helm chart much easier if I don't have to build this locally.

**Comment by samcat116** [comment]
Since there is already a Dockerfile in the repo and its actively using GitHub Actions, it would be great to publish a container to Docker Hub or the Github Container registry for easy access. Personally it would make creating a helm chart much easier if I don't have to build this locally.

**Comment by ibotty** [comment]
This can be closed.  The container image is published to ghcr.io/micromdm/nanomdm:latest and ghcr.io/micromdm/nanomdm:main for the HEAD of the main branch.
