### ISSUE TITLE
Error trying to enroll a iOS device

### ISSUE THREAD

**Issue by sbenedetti21** [micromdm/nanomdm#56]
Hi! I'm new to nanoMDM, I was trying to set it up for testing and followed the steps on `quickstart.md`. When the server was up and running i opened safari on my iphone and went to '{my_local_ip}/mdm' to enroll the device, and then the server responded with a bad request and the logs look like this

```shell
2022/09/07 08:49:02 level=info handler=log addr=192.168.0.90 method=GET path=/mdm agent=Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Mobile/15E148 Safari/604.1
2022/09/07 08:49:02 level=debug handler=cert-extract msg=empty Mdm-Signature header
2022/09/07 08:49:02 level=info handler=cert-verify msg=error verifying MDM certificate err=missing MDM certificate
```

Am I doing something wrong?

The command I'm running is `./nanomdm-darwin-amd64 -ca ca.pem -api nanomdm -debug`

**Comment by jessepeterson** [comment]
The `/mdm` URL is for an Apple MDM client to connect to. You have to provide your device an enrollment profile by either hosting an enrollment profile on a website or, say, emailing it to your device. Hope that's helpful. We can probably be more helpful if you join the #nanomdm channel on the [Slack](https://www.macadmins.org/). :)
