### ISSUE TITLE
pushcert

### ISSUE THREAD

**Issue by paolominel** [micromdm/nanomdm#77]
I tried to build up a nanoMDM instance into a Kubernetes environment...

I started an SCEP server (from micromdm/scep project) and everything was fine.
I also started a nanomdm server (setting into it the prepared ca.pem and push.key) and it started fine.

But when i tried to get a topic id through **"cat ca.pem push.key | curl -T - -u 'nanomdm:MY_PASSWD' 'https://MY_NANOMDM_URL/v1/pushcert'"** command i always obtain this response: **private key does not match public key**.

Nanomdm server is started and listening at port 9000 (port is forwarded by a Kubernetes environment).

For now i'm using a certificate generate by mdmcert.download.

Thanks in advance

**Comment by korylprince** [comment]
It looks like you're mixing up your certificates, so the error is correct.

If you're following the [Quickstart Guide](https://github.com/micromdm/nanomdm/blob/main/docs/quickstart.md), then ca.pem is the CA certificate for your SCEP server. It should be passed to nanomdm with the `-ca` flag.

The push certificate (named push.pem in the Quickstart Guide) will come from Apple. You'll use the certificate request you get from mdmcert.download to get the push certificate from Apple.

If you need further help, I'd suggest reaching out in the #nanomdm channel in the [MacAdmins Slack](https://www.macadmins.org/)
