### ISSUE TITLE
docs/enroll.mobileconfig lacks SCEP Subject

### ISSUE THREAD

**Issue by zhangyoufu** [micromdm/nanomdm#81]
macOS MDM client does not work properly. A client certificate is issued with empty subject and won't be used when connecting to MDM server.

iOS MDM client works without problem.

I end up with subject template like this:
```
<key>Subject</key>
<array>
	<array>
		<array>
			<string>CN</string>
			<string>MDM Client %HardwareUUID%</string>
		</array>
	</array>
	<array>
		<array>
			<string>2.5.4.5</string>
			<string>%SerialNumber%</string>
		</array>
	</array>
</array>
```

**Comment by jessepeterson** [comment]
Do you have these reversed by chance? iOS does not support the `%substiatuion%` variables like macOS does. I.e. on macOS you can do `/usr/libexec/mdmclient dumpSCEPVars` to get the list.

In any case this isn't a MicroMDM problem per se, but an Apple SCEP profile payload issue. If you need the serial number I suggest looking into [ACME (MDA)](https://support.apple.com/guide/deployment/managed-device-attestation-dep28afbde6a/web) for attestation and/or getting the serial number from the [`Authenticate` MDM check-in message](https://developer.apple.com/documentation/devicemanagement/authenticaterequest) for non-User Enrollment enrollments.

**Comment by zhangyoufu** [comment]
> iOS does not support the `%substiatuion%` variables like macOS does

You're right. I didn't notice that. 

> In any case this isn't a MicroMDM problem per se, but an Apple SCEP profile payload issue.

I followed nanomdm quickstart guide and my macOS connect to nanomdm without using client certificate issued by SCEP server. This is a problem IMHO.
